services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always 
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  users:
    container_name: users_service 
    build: 
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres