services:
  testpostgres:
    image: postgres:16-alpine
    container_name: test_postgres
    restart: always 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  testusers:
    container_name: test_users_service 
    command: >
        sh -c "
        npx prisma migrate dev &&
        npm run test:e2e"

    build: 
      context: ../backend/users
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ../backend/users/src:/app/src
      - ../backend/users/test:/app/test
    ports:
      - ${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}
    depends_on:
      testpostgres:
        condition: service_healthy
        restart: true
