services:
  prodpostgres:
    image: postgres:16-alpine
    container_name: prod_postgres 
    restart: always 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  users:
    container_name: prod_users 
    build: 
      dockerfile: ./Dockerfile.production
      context: ../backend/users
      target: prod
    env_file:
      - ./.env
    ports:
      - ${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}
    depends_on:
      prodpostgres:
        condition: service_healthy
        restart: true
